# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=500)),
                ('class_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=500)),
                ('fps', models.CharField(max_length=5)),
                ('engine', models.CharField(max_length=10)),
                ('platform', models.CharField(max_length=10)),
                ('isdoc', models.CharField(max_length=10)),
                ('islod', models.CharField(max_length=10)),
                ('ispbr', models.CharField(max_length=10)),
                ('iscollision', models.CharField(max_length=10)),
                ('vertexcount', models.CharField(max_length=10)),
                ('meshcount', models.CharField(max_length=5)),
                ('texturecount', models.CharField(max_length=10)),
                ('texturesize', models.CharField(max_length=10)),
                ('materialscount', models.CharField(max_length=10)),
                ('animcount', models.CharField(max_length=10)),
                ('effectcount', models.CharField(max_length=10)),
            ],
        ),
    ]
